# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hops Solo Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hops Solo Project
	#https://firebase.google.com/ios/setup#available-pods
pod 'Firebase/Auth'

  target 'Hops Solo ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
